---
title: "Power Calculation Analysis"
author: "Kennedy Flavin"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("C:/Users/Kennedy Flavin/Dropbox/PC/Desktop/WINTER 24/262 Computing ENV SCI/262Flavin/assignments/assignments/power_calculation.R")
```

## R Markdown
```{r}
#Parameters for heavy truck
m_heavy_truck <- 31752
A_heavy_truck <- 16

#speeds
speeds <- c(30,80,120,40,5)

# create a new plot
plot.new()

# calculate power for heavy truck
power_heavy_truck <- sapply(speeds, function(speed) calculate_power(m_heavy_truck, A_heavy_truck, speed))

#Plot 
plot(speeds, power_heavy_truck, type = "o", col = "blue", xlab = "Speed (km/hr)", ylab = "Power (Watts)", main = "Power vs Speed - Heavy Truck" )

```

```{r}
# Parameters for lighter vehicle
m_lighter_vehicle <- 15000
A_lighter_vehicle <- 16

# create a new plot
plot.new()

# Calculate power for lighter vehicle
power_lighter_vehicle <- sapply(speeds, function(speed) calculate_power(m_lighter_vehicle, A_lighter_vehicle, speed))

# Set graphical parameters to ensure both lines are on the same plot
par(mfrow = c(1, 1))

# Plot
plot(speeds, power_heavy_truck, type = "o", col = "blue", xlab = "Speed (km/hr)", ylab = "Power (Watts)",
     main = "Power vs Speed", ylim = range(c(power_heavy_truck, power_lighter_vehicle)))

# Add second line for the lighter vehicle
lines(speeds, power_lighter_vehicle, type = "o", col = "red")

# Add legend
legend("topright", legend = c("Heavy Truck", "Lighter Vehicle"), col = c("blue", "red"), lty = 1)

```





